name: Upload data to production database on release

on:
  release:
    types: [released]

env:
  REQUEST_TIMEOUT: 300

jobs:
  publish:
    uses: geological-survey-of-queensland/vocabularies/.github/workflows/upload_to_database.yml@master
    with:
      request_timeout: ${{ env.REQUEST_TIMEOUT }}
    secrets:
      database_url: ${{ secrets.FUSEKI_DATASET_URL }}
      database_username: ${{ secrets.FUSEKI_USERNAME }}
      database_password: ${{ secrets.FUSEKI_PASSWORD }}
